// codegen is a workspace-built tool: it writes a small generated Go source file into the
// current working directory when run with no arguments. Sindri runs it during the `generate`
// step of any module that names it in `module_tools`, with the working directory set to that
// module's own directory — so the generated file lands in the consuming module's source tree,
// where its ordinary `compile` step picks it up in the same build.
package main

import "os"

const generated = `// Code generated by codegen. DO NOT EDIT.

package main

func generatedGreeting() string {
	return "Hello from codegen!"
}
`

func main() {
	if err := os.WriteFile("generated_greeting.go", []byte(generated), 0o644); err != nil {
		panic(err)
	}
}
